# Generated by Django 5.2.7 on 2025-11-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="book_fee",
            field=models.IntegerField(default=0),
        ),
    ]
